import Project from "./Project";
import gerontovida from './imagenes/gerontovida/gerontovida-imagen.webp'
import login from './imagenes/gerontovida/login.webp'
import api from './imagenes/gerontovida/api.webp'
import login2 from './imagenes/gerontovida/login-2.png'
import login3 from './imagenes/gerontovida/login-3.png'
import escritorio from './imagenes/gerontovida/escritorio.png'
import publicarCanasta from './imagenes/gerontovida/publicarCanasta.png'
import canastaBarra from './imagenes/gerontovida/canasta-barra.png'
import canastaTorta from './imagenes/gerontovida/canasta-torta.png'
import portadaGeronto from './imagenes/gerontovida/portadaGeronto.svg'
import '../App.css'


export default function Gerontovida() {


    const imagenes = [
        { label: 'login', imgPath: login }, { label: 'reset password', imgPath: login2 }, { label: 'register', imgPath: login3 },
        { label: 'edit articles', imgPath: escritorio }, { label: 'publish charts', imgPath: publicarCanasta }, { label: 'charts', imgPath: canastaBarra }, { label: 'donut chart', imgPath: canastaTorta }]

    return (
        <div>
            <div className="flex flex-col justify-center items-center">

                <br />
                <div className="container max-w-[100%]">
                    <div className="w-[350px]">
                        <img src={portadaGeronto} alt="Muestra del sitio Gerontovida" />
                    </div>
                    <div className=" flex flex-col  gap-[10px] max-w-[95%] p-6 md:flex-row justify-center ">
                        <Project
                            name={'- Public Site -'}
                            excerpt={'Articles, charts and information'}
                            image={gerontovida}
                            generalInfo={"This is a sample of the Gerontovida Association website. The information and data presented here are generated by random functions and, in no case, represent real data."}
                            techInfo={"The front-end is developed using React, Redux, ReactBootstrap, Styled-Components, and React-Chart for the charts, among other technologies. The entire public section of the site is responsive."}
                            site={"https://gerontovida-muestra.netlify.app/"}
                            repo={"https://github.com/semino-dario/gerontovida"}
                        />
                        <br />
                        <br />
                        <Project
                            imagenes={imagenes}
                            techInfo={"This is the login section of the site. User authentication and session management are carried out through a token generated using JSON Web Tokens (JWT). API queries are conducted using Axios. This section is not responsive."}
                            generalInfo={"In this sample of the site, it's possible to perform operations to register as a user and access the dashboard to publish, edit, or delete articles in the news section. It's also possible to recover the password and access information about the logged-in user. In the Canasta section, it's possible to publish, edit, or delete any of the Canasta's charts. Additionally, you can upload a PDF file with information about the chart, which can be downloaded later."}
                            site={"https://gerontovida-muestra.netlify.app/sesion"}
                            repo={"https://github.com/semino-dario/gerontovida"}
                        />
                        <br />
                        <br />
                        <Project
                            name={'- Backend -'}
                            excerpt={'API with Node JS and Mongo DB'}
                            image={api}
                            techInfo={"This API was developed with Node.js, Exprees, and Mongo DB. It's hosted in Cyclic.  The images for articles and PDF files are loaded into an AWS S3 bucket."}
                            generalInfo={"This API handles different kind of writen content, for example articles for different blog applications. It also has all the typital authentication functionalities for users with Jason Web Token (JWT). This version is a sample of the real application, in which some functionalities such as password recovery email sending are disabled."}
                            site={"https://api-contenidos.cyclic.app/"}
                            repo={"https://github.com/semino-dario/api-contenidos"}
                        />
                        <br />
                    </div>
                    <br />
                </div>
                <br /> <br />
            </div>
        </div>

    )
}