export const cursos = [
  {
    escuela: "Scrimba",
    curso: "What's new in React 19",
    año: "2025",
    horas: "1.1 hs",
    imagen: "/images/logos/scrimba.jpg",
    credencial: "/images/credenciales/react-19.png",
    id: 8,
  },
  {
    escuela: "Scrimba",
    curso: "Build Reusable React Components",
    año: "2025",
    horas: "3.6 hs",
    imagen: "/images/logos/scrimba.jpg",
    credencial: "/images/credenciales/credencial-reusable.png",
    id: 7,
  },
  {
    escuela: "Scrimba",
    curso: "Javascript Deep Dive",
    año: "2024",
    horas: "14.1 hs",
    imagen: "/images/logos/scrimba.jpg",
    credencial: "/images/credenciales/js-deep.png",
    id: 6,
  },

  {
    escuela: "Scrimba",
    curso: "Learn Typescript",
    año: "2024",
    horas: "2.1 hs",
    imagen: "/images/logos/scrimba.jpg",
    credencial: "/images/credenciales/typescript.png",
    id: 5,
  },

  {
    escuela: "Scrimba",
    curso: "Introduction to Es6+",
    año: "2024",
    horas: "2 hs",
    imagen: "/images/logos/scrimba.jpg",
    credencial: "/images/credenciales/es6.png",
    id: 4,
  },
  {
    escuela: "Scrimba",
    curso: "Introduction to Clean Code",
    año: "2024",
    horas: "1.1 hs",
    imagen: "/images/logos/scrimba.jpg",
    credencial: "/images/credenciales/clean-code.png",
    id: 3,
  },
  {
    escuela: "Udemy",
    curso: "Node.js - The Complete RESTful API Masterclass",
    año: "2023",
    horas: "11 hs",
    imagen: "/images/logos/udemy.svg",
    credencial: "/images/credenciales/credencial-udemy.webp",
    id: 2,
  },
  {
    escuela: "Educación IT",
    curso: "React.JS Developer",
    año: "2023",
    horas: "36 hs",
    imagen: "/images/logos/it.png",
    credencial: "/images/credenciales/credencial-it.webp",
    id: 1,
  },
  {
    escuela: "Plataforma 5",
    curso: "Scrum Master Program / Curso Introductorio de Programación",
    año: "2022",
    horas: "54 hs",
    imagen: "/images/logos/p5.png",
    credencial: "images/credenciales/credencial-p5.webp",
    id: 0,
  },
];
